name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_wrapper: false

      - name: Terraform Format Check
        run: terraform fmt -recursive -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.0
        with:
          tflint_version: v0.64.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [validate, tflint]
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Test
        run: terraform test
